executable("broker") {
  sources = [
    "broker/algobroker.cc",
    "broker/algobroker.h",
  ]

  defines = [ "ALGO_BROKER_EXPORTS" ]

  deps = [
    "//base",
    "//sandbox/linux:sandbox",
    "//sandbox/policy",
  ]

  output_name = "algobroker.netcore"
}

executable("host") {
  sources = [
    "host/algohost.cc",
    "host/algohost.h",
    "host/native_host/nativehost.cc",
    "host/native_host/nativehost.h",
    "host/native_host/inc/nethost.h",
    "host/native_host/inc/hostfxr.h",
    "host/native_host/inc/coreclr_delegates.h",
  ]

  include_dirs = [
    "host/native_host/inc"
  ]

  lib_dirs = [
    "host/native_host/libs"
  ]

  libs = [
    "nethost",
  ]

  defines = [ "ALGO_BROKER_EXPORTS" ]

  deps = [
    "//base",
    "//sandbox/linux:sandbox",
    "//sandbox/policy",
    ":copy_nethost",
    ":copy_config",
  ]

  output_name = "algohost.netcore"
}

copy("copy_nethost") {
  sources = [ "host/native_host/libs/libnethost.so" ]
  outputs = [ "$root_out_dir/libnethost.so" ]
}

copy("copy_config") {
  sources = [ "host/native_host/DotNetLib.runtimeconfig.json" ]
  outputs = [ "$root_out_dir/testing_app/DotNetLib.runtimeconfig.json" ]
}
