shared_library("broker") {
  sources = [
    "broker/algobroker.cc",
    "broker/algobroker.h",
  ]

  defines = [ "ALGO_BROKER_EXPORTS" ]

  deps = [
    "//sandbox/win:sandbox",
  ]

  output_name = "algobroker.netcore"
}

executable("host") {
  sources = [
    "host/algohost.cc",
    "host/algohost.h",
    "host/coreclr_delegates.h",
    "host/vars.h",
  ]

  deps = [
    "//sandbox/win:sandbox",
  ]

  output_name = "algohost.netcore"
}
