executable("the_one") {
  sources = [
    "broker/algobroker.h",
    "broker/algobroker.cc",
    "broker/host.cc",
    "host/algohost.cc",
    "host/algohost.h",
    "host/coreclr_delegates.h",
    "host/vars.h",
  ]

  deps = [
    "//third_party/abseil-cpp:absl",
    "//sandbox/win:sandbox",
    ":copy_tasks",
  ]

  output_name = "algohost"
}

executable("launcher") {
  sources = [
    "launcher/launcher.cc",
  ]

  output_name = "launcher"
}

copy("copy_tasks") {
  sources = [ "launcher/task.json" ]
  outputs = [ "$root_out_dir/task.json" ]
}
